services:
  db:
    image: postgres:13
    container_name: db4
    environment:
      POSTGRES_DB: gestion_produits
      POSTGRES_PASSWORD: root
    volumes:
      - ./database/gestion_produits.sql:/docker-entrypoint-initdb.d/gestion_produits.sql
    networks:
      - default

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web4
    ports:
      - "8080:80"
    volumes:
      - ./www/:/var/www/html/
    depends_on:
      - db
    networks:
      - default
    env_file:
      - .env.production

networks:
  default:
    name: my_network4
